# This is the config file for OxideWM.
# TODO: Insert Information from ./examples/config_man_page.md

cmds:
  #WM Commands
  - keys: ["A", "S", "e"]
    command: Quit
    args: None

  - keys: ["A", "S", "r"]
    command: Restart
    args: None

  - keys: ["A", "S", "q"]
    command: Kill
    args: None

  # Move Focus
  - keys: ["A", "l"]
    command: Focus
    args: "right"

  - keys: ["A", "h"]
    command: Focus
    args: "left"

  # Move Windows
  - keys: ["A", "S", "l"]
    command: Move
    args: "right"

  - keys: ["A", "S", "h"]
    command: Move
    args: "left"

  # Toggle Fullscreen
  - keys: ["A", "f"]
    command: Fullscreen
    args: None

  # Change Layout
  - keys: ["A", "u"]
    command: Layout
    args: None

  - keys: ["A", "i"]
    command: Layout
    args: "Vertical"

  - keys: ["A", "S", "i"]
    command: Layout
    args: "horizontal"

  - keys: ["A", "d"]
    command: Exec
    args: "dmenu_run"

  # Workspace keys configuration
  - keys: ["C", "A", "Right"]
    command: GoToWorkspace
    args: "next"

  - keys: ["C", "A", "Left"]
    command: GoToWorkspace
    args: "previous"

  # Execute Commands
  - keys: ["A", "d"]
    command: Exec
    args: "dmenu_run"

  - keys: ["A", "t"]
    command: Exec
    args: "kitty"

exec: ["./target/debug/oxide-bar"]
exec_always: []
border_with: 8
# Colors have to be entered in hexadacinmal
border_color: "0x008000" # yellow
border_focus_color: "0xFFFF00" # green
gap: 8
