# This is the config file for OxideWM.
# Here you can freely configure your window manager.
# Please keep in mind that you have to configure every value properly for the WM to run, otherwise the programm will crash.
#
# OxideWM uses the 'Alt' key as the meta key
# Key shortcuts:
# - A -> ALT
# - C -> CONTROL
# - S -> SHIFT
#
# Move commands:
# - left
# - right
# - up
# - down
#
# WmCommands:
# - Exec
# - Focus
# - GoToWorkspace
# - Kill: kill the focused window
# - Layout, args: horizontal, Vertical
# - Move, args: left, right, up, down
# - MoveToWorkspace
# - MoveToWorkspaceAndFollow
# - Quit: quit the window manager
# - Resize
# - Restart: restart the window manager
#
# In 'cmds' all keybindings for the WM are defined.
# A Command consists of an array of keys, the command, some optional arguments and should be configured like the following:
# - keys: ["A", "t"]
#   command: Exec
#   args: "kitty"
# In this example, the command opens a kitty window.

cmds:
  - keys: ["A", "t"]
    command: Exec
    args: "kitty"

  - keys: ["A", "S", "e"]
    command: Quit
    args: None

  - keys: ["A", "S", "r"]
    command: Restart
    args: None

  - keys: ["A", "S", "q"]
    command: Kill
    args: None

  - keys: ["A", "l"]
    command: Focus
    args: "right"

  - keys: ["A", "S", "l"]
    command: Move
    args: "right"

  - keys: ["A", "S", "h"]
    command: Move
    args: "left"

  - keys: ["A", "h"]
    command: Focus
    args: "left"

  - keys: ["A", "u"]
    command: Layout
    args: None

  - keys: ["A", "i"]
    command: Layout
    args: "Vertical"

  - keys: ["A", "S", "i"]
    command: Layout
    args: "horizontal"

  - keys: ["A", "d"]
    command: Exec
    args: "dmenu_run"

  # Workspace keys configuration
  - keys: ["C", "A", "Right"]
    command: GoToWorkspace
    args: "next"

  - keys: ["C", "A", "Left"]
    command: GoToWorkspace
    args: "previous"

exec: ["./target/debug/oxide-bar"]
exec_always: []
border_with: 8
# Colors have to be entered in hexadacinmal
border_color: "0x008000" # yellow
border_focus_color: "0xFFFF00" # green
gap: 8
