# This is the config file for OxideWM.
# Here you can freely configure your window manager.
# Please keep in mind that you have to configure every value properly for the WM to run.
# Otherwise the programm will crash.

cmds:
  #WM Commands
  - keys: ["A", "S", "e"]
    command: Quit
    args: None

  - keys: ["A", "S", "r"]
    command: Restart
    args: None

  - keys: ["A", "S", "q"]
    command: Kill
    args: None

  # Move Focus
  - keys: ["A", "l"]
    command: Focus
    args: "right"

  - keys: ["A", "h"]
    command: Focus
    args: "left"

  # Move Windows
  - keys: ["A", "S", "l"]
    command: Move
    args: "right"

  - keys: ["A", "S", "h"]
    command: Move
    args: "left"

  # Toggle Fullscreen
  - keys: ["A", "f"]
    command: Fullscreen
    args: None

  # Change Layout
  - keys: ["A", "u"]
    command: Layout
    args: None

  - keys: ["A", "i"]
    command: Layout
    args: "Vertical"

  - keys: ["A", "S", "i"]
    command: Layout
    args: "horizontal"
      
  #Workspace keys configuration
  - keys: ["C","A", "Right"]
    command: GoToWorkspace
    args: "next"

  - keys: ["C","A", "Left"]
    command: GoToWorkspace
    args: "previous"

  # Execute Commands
  - keys: ["A", "d"]
    command: Exec
    args: "dmenu_run"
  
  - keys: ["A", "t"]
    command: Exec
    args: "kitty"

exec: ["./target/debug/oxide-bar"]
exec_always: []
border_with: 8
border_color: "0x008000" # yellow
border_focus_color: "0xFFFF00" # green
gap: 8
