# This is a comment.
WmCommand:
Data:
  - keys:
    command:
    args:

UserCommand:
  - keys:
    command:

Config:
  - cmds:
    user_cmds:
    exec:
    exec_always:
    border_with:
    border_color:
    border_focus_color:
    titlebar:
    command:
