---
update_frequency_sec: 120
num_threads: 2
data_sources:
  - name: Google News
    url: news.google.com
    source_type: news
  - name: Yahoo Finance
    url: finance.yahoo.com
    source_type: financial news
  - name: Microsoft News
    url: www.msn.com
    source_type: news
  - name: NYTimes
    url: www.nytimes.com
    source_type: news
  - name: Yahoo News
    url: news.yahoo.com
    source_type: news
