[package]
name = "oxide-msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxideipc = { version = "0.1", path = "../oxide-ipc" }
clap = { version = "4.0.*", features = ["derive"] }
