name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build oxide wm
      run: cargo build
    - name: Build examples
      run: cargo build --examples
    - name: Build oxide bar
      run: cargo build -p oxide-bar
    - name: Build ipc lib
      run: cargo build -p oxideipc
    - name: Build oxide msg
      run: cargo build -p oxide-msg
